name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: sudo docker pull $DOCKER_USER/bikeshare_sharing_api:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f bikeshare_sharing_api-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: sudo docker run -it -d -p 8001:8001 --name bikeshare_sharing_api-container $DOCKER_USER/bikeshare_sharing_api:latest
