name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Clear Runner Cache
      run: rm -rf ~/.npm ~/.cache ~/.pip
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python bikeshare_model/train_pipeline.py
    - name: Upload trained pipeline
      uses: actions/upload-artifact@v4
      with:
        name: my-trained-pipeline
        path: bikeshare_model/trained_models/*.pkl
        retention-days: 1

  test:
  needs: train
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'
    - uses: actions/download-artifact@v3
      with:
        name: my-trained-pipeline
        path: bikeshare_model/trained_models
    - name: Install Dependencies
      run: pip install -r requirements/test_requirements.txt
    - name: Test with pytest
      run: pytest
  