name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
      - name: Install dependencies
        run: pip install -r requirements/requirements.txt
      - name: Train and save pipeline
        run: python bikeshare_model/train_pipeline.py
      - name: Upload trained pipeline
        uses: actions/upload-artifact@v3
        with:
          name: my-trained-pipeline
          path: bikeshare_model/trained_models/*.pkl
          retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
      - uses: actions/download-artifact@v3
        with:
          name: my-trained-pipeline
          path: bikeshare_model/trained_models
      - name: Install Dependencies
        run: pip install -r requirements/test_requirements.txt
      - name: Test with pytest
        run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
      - uses: actions/download-artifact@v3
        with:
          name: my-trained-pipeline
          path: bikeshare_model/trained_models
      - name: Install Dependencies
        run: pip install --upgrade build
      - name: Build package
        run: python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: my-build-package
          path: dist/*.whl
          retention-days: 1

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: my-build-package
          path: bike_sharing_api

      - name: Login to Docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image for FastAPI app
        run: |
          cd bike_sharing_api
          docker build . -f Dockerfile -t bike_sharing_api:latest

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_USER/bike_sharing_api:latest